web:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./nginx.conf.d:/etc/nginx/nginx.conf.d
    - ./log:/var/log/nginx
    - ./docroot:/usr/share/nginx/html
  ports:
    - 80:80
