version: "3"

services:
  web:
    image: nginx
    logging:
      driver: syslog
      options:
        tag: "nginx_{{.ID}}"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/nginx.conf.d
      - ./docroot:/usr/share/nginx/html
    ports:
      - 80:80
